<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Supported Countries (ISO-3166-1 Alpha-2)
    | Used by Meta geo_locations.countries
    |--------------------------------------------------------------------------
    */

    'countries' => [

        'AF'=>'Afghanistan',
        'AL'=>'Albania',
        'DZ'=>'Algeria',
        'AD'=>'Andorra',
        'AO'=>'Angola',
        'AG'=>'Antigua and Barbuda',
        'AR'=>'Argentina',
        'AM'=>'Armenia',
        'AU'=>'Australia',
        'AT'=>'Austria',
        'AZ'=>'Azerbaijan',
        'BS'=>'Bahamas',
        'BH'=>'Bahrain',
        'BD'=>'Bangladesh',
        'BB'=>'Barbados',
        'BY'=>'Belarus',
        'BE'=>'Belgium',
        'BZ'=>'Belize',
        'BJ'=>'Benin',
        'BT'=>'Bhutan',
        'BO'=>'Bolivia',
        'BA'=>'Bosnia and Herzegovina',
        'BW'=>'Botswana',
        'BR'=>'Brazil',
        'BN'=>'Brunei',
        'BG'=>'Bulgaria',
        'BF'=>'Burkina Faso',
        'BI'=>'Burundi',
        'KH'=>'Cambodia',
        'CM'=>'Cameroon',
        'CA'=>'Canada',
        'CV'=>'Cape Verde',
        'CF'=>'Central African Republic',
        'TD'=>'Chad',
        'CL'=>'Chile',
        'CN'=>'China',
        'CO'=>'Colombia',
        'KM'=>'Comoros',
        'CG'=>'Congo',
        'CD'=>'Congo (DRC)',
        'CR'=>'Costa Rica',
        'CI'=>"Côte d'Ivoire",
        'HR'=>'Croatia',
        'CU'=>'Cuba',
        'CY'=>'Cyprus',
        'CZ'=>'Czech Republic',
        'DK'=>'Denmark',
        'DJ'=>'Djibouti',
        'DM'=>'Dominica',
        'DO'=>'Dominican Republic',
        'EC'=>'Ecuador',
        'EG'=>'Egypt',
        'SV'=>'El Salvador',
        'GQ'=>'Equatorial Guinea',
        'ER'=>'Eritrea',
        'EE'=>'Estonia',
        'ET'=>'Ethiopia',
        'FJ'=>'Fiji',
        'FI'=>'Finland',
        'FR'=>'France',
        'GA'=>'Gabon',
        'GM'=>'Gambia',
        'GE'=>'Georgia',
        'DE'=>'Germany',
        'GH'=>'Ghana',
        'GR'=>'Greece',
        'GD'=>'Grenada',
        'GT'=>'Guatemala',
        'GN'=>'Guinea',
        'GW'=>'Guinea-Bissau',
        'GY'=>'Guyana',
        'HT'=>'Haiti',
        'HN'=>'Honduras',
        'HU'=>'Hungary',
        'IS'=>'Iceland',
        'IN'=>'India',
        'ID'=>'Indonesia',
        'IR'=>'Iran',
        'IQ'=>'Iraq',
        'IE'=>'Ireland',
        'IL'=>'Israel',
        'IT'=>'Italy',
        'JM'=>'Jamaica',
        'JP'=>'Japan',
        'JO'=>'Jordan',
        'KZ'=>'Kazakhstan',
        'KE'=>'Kenya',
        'KI'=>'Kiribati',
        'KW'=>'Kuwait',
        'KG'=>'Kyrgyzstan',
        'LA'=>'Laos',
        'LV'=>'Latvia',
        'LB'=>'Lebanon',
        'LS'=>'Lesotho',
        'LR'=>'Liberia',
        'LY'=>'Libya',
        'LI'=>'Liechtenstein',
        'LT'=>'Lithuania',
        'LU'=>'Luxembourg',
        'MG'=>'Madagascar',
        'MW'=>'Malawi',
        'MY'=>'Malaysia',
        'MV'=>'Maldives',
        'ML'=>'Mali',
        'MT'=>'Malta',
        'MH'=>'Marshall Islands',
        'MR'=>'Mauritania',
        'MU'=>'Mauritius',
        'MX'=>'Mexico',
        'FM'=>'Micronesia',
        'MD'=>'Moldova',
        'MC'=>'Monaco',
        'MN'=>'Mongolia',
        'ME'=>'Montenegro',
        'MA'=>'Morocco',
        'MZ'=>'Mozambique',
        'MM'=>'Myanmar',
        'NA'=>'Namibia',
        'NR'=>'Nauru',
        'NP'=>'Nepal',
        'NL'=>'Netherlands',
        'NZ'=>'New Zealand',
        'NI'=>'Nicaragua',
        'NE'=>'Niger',
        'NG'=>'Nigeria',
        'KP'=>'North Korea',
        'MK'=>'North Macedonia',
        'NO'=>'Norway',
        'OM'=>'Oman',
        'PK'=>'Pakistan',
        'PW'=>'Palau',
        'PA'=>'Panama',
        'PG'=>'Papua New Guinea',
        'PY'=>'Paraguay',
        'PE'=>'Peru',
        'PH'=>'Philippines',
        'PL'=>'Poland',
        'PT'=>'Portugal',
        'QA'=>'Qatar',
        'RO'=>'Romania',
        'RU'=>'Russia',
        'RW'=>'Rwanda',
        'KN'=>'Saint Kitts and Nevis',
        'LC'=>'Saint Lucia',
        'VC'=>'Saint Vincent and the Grenadines',
        'WS'=>'Samoa',
        'SM'=>'San Marino',
        'ST'=>'São Tomé and Príncipe',
        'SA'=>'Saudi Arabia',
        'SN'=>'Senegal',
        'RS'=>'Serbia',
        'SC'=>'Seychelles',
        'SL'=>'Sierra Leone',
        'SG'=>'Singapore',
        'SK'=>'Slovakia',
        'SI'=>'Slovenia',
        'SB'=>'Solomon Islands',
        'SO'=>'Somalia',
        'ZA'=>'South Africa',
        'KR'=>'South Korea',
        'SS'=>'South Sudan',
        'ES'=>'Spain',
        'LK'=>'Sri Lanka',
        'SD'=>'Sudan',
        'SR'=>'Suriname',
        'SZ'=>'Eswatini',
        'SE'=>'Sweden',
        'CH'=>'Switzerland',
        'SY'=>'Syria',
        'TW'=>'Taiwan',
        'TJ'=>'Tajikistan',
        'TZ'=>'Tanzania',
        'TH'=>'Thailand',
        'TL'=>'Timor-Leste',
        'TG'=>'Togo',
        'TO'=>'Tonga',
        'TT'=>'Trinidad and Tobago',
        'TN'=>'Tunisia',
        'TR'=>'Turkey',
        'TM'=>'Turkmenistan',
        'TV'=>'Tuvalu',
        'UG'=>'Uganda',
        'UA'=>'Ukraine',
        'AE'=>'United Arab Emirates',
        'GB'=>'United Kingdom',
        'US'=>'United States',
        'UY'=>'Uruguay',
        'UZ'=>'Uzbekistan',
        'VU'=>'Vanuatu',
        'VA'=>'Vatican City',
        'VE'=>'Venezuela',
        'VN'=>'Vietnam',
        'YE'=>'Yemen',
        'ZM'=>'Zambia',
        'ZW'=>'Zimbabwe',

    ],

   /*
|--------------------------------------------------------------------------
| Languages (Meta Locale IDs)
| Used by targeting.locales
|--------------------------------------------------------------------------
*/

'languages' => [

1000 => 'English (All)',
1001 => 'Arabic',
1002 => 'Spanish',
1003 => 'Hindi',
1004 => 'French',
1005 => 'German',
1006 => 'Italian',
1007 => 'Portuguese',
1008 => 'Russian',
1009 => 'Chinese (Simplified)',
1010 => 'Chinese (Traditional)',
1011 => 'Japanese',
1012 => 'Korean',
1013 => 'Dutch',
1014 => 'Swedish',
1015 => 'Danish',
1016 => 'Finnish',
1017 => 'Norwegian',
1018 => 'Polish',
1019 => 'Turkish',
1020 => 'Thai',
1021 => 'Vietnamese',
1022 => 'Indonesian',
1023 => 'Malay'

]

];